version: '3.8'

services:
  jekyll:
    image: jekyll/jekyll:latest
    container_name: jekyll-blog
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll:Z
      - ./_site:/srv/jekyll/_site:Z
    environment:
      - JEKYLL_ENV=development
    command: >
      bash -c "bundle install &&
               bundle exec jekyll serve 
               --host 0.0.0.0 
               --port 4000 
               --livereload 
               --incremental 
               --drafts 
               --force_polling"
    stdin_open: true
    tty: true